select *
from DIM_COMBUSTIVEL

SELECT *
FROM DIM_LOCALIDADE

SELECT *
FROM DIM_TEMPO

SELECT *
FROM FATO_VENDAS_COMBUSTIVEL

SELECT *
FROM FATO_COTACAO




ALTER TABLE DIM_COMBUSTIVEL ALTER COLUMN id BIGINT NOT NULL

ALTER TABLE DIM_COMBUSTIVEL
ADD CONSTRAINT PK_DimCombustivel
PRIMARY KEY (id);

ALTER TABLE DIM_LOCALIDADE ALTER COLUMN id BIGINT NOT NULL

ALTER TABLE DIM_LOCALIDADE
ADD CONSTRAINT PK_DimLocalidade
PRIMARY KEY (id);

ALTER TABLE DIM_TEMPO ALTER COLUMN id BIGINT NOT NULL

ALTER TABLE DIM_TEMPO
ADD CONSTRAINT PK_DimTempo
PRIMARY KEY (id);

ALTER TABLE FATO_VENDAS_COMBUSTIVEL
ADD CONSTRAINT FK_FatoVendasCombustivel_DimCombustivel
FOREIGN KEY (COMBUSTIVEL)
REFERENCES DIM_COMBUSTIVEL(id);

ALTER TABLE FATO_VENDAS_COMBUSTIVEL
ADD CONSTRAINT FK_FatoVendasCombustivel_DimLocalidade
FOREIGN KEY (LOCALIDADE)
REFERENCES DIM_LOCALIDADE(id);

ALTER TABLE FATO_VENDAS_COMBUSTIVEL
ADD CONSTRAINT FK_FatoVendasCombustivel_DimTempo
FOREIGN KEY (ANO)
REFERENCES DIM_TEMPO(id);

ALTER TABLE FATO_COTACAO ALTER COLUMN COMBUSTIVEL BIGINT

ALTER TABLE FATO_COTACAO ALTER COLUMN LOCALIDADE BIGINT

ALTER TABLE FATO_COTACAO ALTER COLUMN ANO BIGINT

ALTER TABLE FATO_COTACAO
ADD CONSTRAINT FK_FatoCotacao_DimTempo
FOREIGN KEY (ANO)
REFERENCES DIM_TEMPO(id);

ALTER TABLE FATO_COTACAO
ADD CONSTRAINT FK_FatoCotacao_DimCombustivel
FOREIGN KEY (COMBUSTIVEL)
REFERENCES DIM_COMBUSTIVEL(id);

ALTER TABLE FATO_COTACAO
ADD CONSTRAINT FK_FatoCotacao_DimLocalidade
FOREIGN KEY (LOCALIDADE)
REFERENCES DIM_LOCALIDADE(id);

